### ISSUE TITLE
your demo, site key invalid

### ISSUE THREAD

**Issue by jackttcoms** [nduhamell/recaptcha-home-page#1]
your demo, site key invalid. Also this is awesome but something that would be even better and more useful would be to have a throttle. 

If you hit the refresh button too many times in a short period of time u are sent to the recaptcha to prove you are not a robot etc.? Google do it.

Thanks

**Comment by rajatgoel789** [comment]
+1

**Comment by nduhamell** [comment]
Demo fixed and updated in README, access at: https://files.nateduhamell.com/demo/recaptcha-home-page/

Have a great day!
